# These are supported funding model platforms

# github: # Reemplazar con hasta 4 nombres de usuario habilitados para patrocinadores de GitHub e.g., [user1, user2]
patreon: NicolhettiProjects
ko_fi: nicolhetti
